// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Hardcoded para garantir conexão com o projeto antigo, ignorando as varíaveis do Lovable
const SUPABASE_URL = "https://apdaqtetajxzpaofdgvu.supabase.co";
const SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFwZGFxdGV0YWp4enBhb2Z1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzI2NzUwNDYsImV4cCI6MjA4ODI1MTA0Nn0.ruFKCfnVaR8N-Cb6E1b_5Euq9FKFCGre4KwCRENoAyo";
export const STORAGE_BUCKET = 'logos';

if (!SUPABASE_URL || !SUPABASE_ANON_KEY) {
  throw new Error('Supabase client requires VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY to be set.');
}

console.log('SUPABASE URL ATUAL:', SUPABASE_URL);
console.log('SUPABASE PROJECT ID ATUAL:', SUPABASE_URL?.match(/\/\/([^.]+)\./)?.[1]);

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_ANON_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});